title: Lucas Bucht
tagline: "Electrical engineer interested in audio electronics and integrated circuits."
banner_image: "/assets/img/banner_image.jpg"
headshot_image: "/assets/img/headshot.jpg"
description: >-
  Electrical Engineer, Resident Assistant, Makerspace Mentor, Leadership Facilitator - Lucas Bucht
url: "https://lucasbucht.github.io"
baseurl: ""

author:
  name: Lucas Bucht
  github: lucasbucht
  linkedin: "https://www.linkedin.com/in/lucasbucht/"
  email: "mailto:lmb290@pitt.edu"

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules